In [1]:
#Agenda
#Why do we need to save arrays to hard drive?
#Saving Single Array
#Loading Single Array
#Saving Multiple Array
#Loading Multiple Array
#Saving array to text file
#Loading array from text file
#What is a delimiter?

In [2]:
import numpy as np

In [3]:
arr= np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Why do we need to save arrays to hard drive?
#   Due to the occurence of Memory Block

In [5]:
#Saving Single Array
np.save("Saved_Array", arr)

In [6]:
#Loading Single Array
Load_Array1= np.load("Saved_Array.npy")
print(Load_Array1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
#Saving Multiple Array
arr2= np.arange(25)
arr3= np.arange(5)

np.savez("Saved_Archeive.npz", x= arr2, y= arr3)


In [8]:
#Loading Multiple Array
Load_npz= np.load("Saved_Archeive.npz")
print(Load_npz['x'])
print(Load_npz['y'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4]


In [9]:
#Saving array to text file

np.savetxt("myarray.txt", arr2, delimiter= ',')

In [10]:
#Loading array from text file
load_file= np.loadtxt("myarray.txt", delimiter= ",")
print(load_file)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


In [11]:
#What is a delimiter?