In [1]:
#Agenda
#What is Concatenation
#Concatenation of Numpy arrays
#Concatenation of Pandas Series
#Concatenation of Pandas DataFrames

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
#Concatenation of Numpy arrays
A1= np.arange(25).reshape(5,5)
B1= np.random.randn(25).reshape(5,5)
print(A1)
print(B1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[-1.45119164 -0.2180474   0.50112883 -1.12957967  1.32004678]
 [-0.48878863  0.97453499  2.00845705  0.69196609  0.94460828]
 [-0.10927602  0.45811422 -0.85928242  0.31057118  0.69356463]
 [-1.19462062  0.52607203 -1.42268197 -0.82891358  1.30518231]
 [ 0.7016282  -0.19730598  0.97203616 -1.24366171  0.30115182]]


In [4]:
np.concatenate([A1, B1], axis= 1)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
        -1.45119164, -0.2180474 ,  0.50112883, -1.12957967,  1.32004678],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
        -0.48878863,  0.97453499,  2.00845705,  0.69196609,  0.94460828],
       [10.        , 11.        , 12.        , 13.        , 14.        ,
        -0.10927602,  0.45811422, -0.85928242,  0.31057118,  0.69356463],
       [15.        , 16.        , 17.        , 18.        , 19.        ,
        -1.19462062,  0.52607203, -1.42268197, -0.82891358,  1.30518231],
       [20.        , 21.        , 22.        , 23.        , 24.        ,
         0.7016282 , -0.19730598,  0.97203616, -1.24366171,  0.30115182]])

In [5]:
np.concatenate([A1, B1], axis= 0)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ],
       [10.        , 11.        , 12.        , 13.        , 14.        ],
       [15.        , 16.        , 17.        , 18.        , 19.        ],
       [20.        , 21.        , 22.        , 23.        , 24.        ],
       [-1.45119164, -0.2180474 ,  0.50112883, -1.12957967,  1.32004678],
       [-0.48878863,  0.97453499,  2.00845705,  0.69196609,  0.94460828],
       [-0.10927602,  0.45811422, -0.85928242,  0.31057118,  0.69356463],
       [-1.19462062,  0.52607203, -1.42268197, -0.82891358,  1.30518231],
       [ 0.7016282 , -0.19730598,  0.97203616, -1.24366171,  0.30115182]])

In [6]:
#Concatenation of Pandas Series
s1= Series([100,200,300], index= list("ABC"))
s2= Series([400,500], index= list("DE"))
print(s1)
print(s2)

A    100
B    200
C    300
dtype: int64
D    400
E    500
dtype: int64


In [7]:
pd.concat([s1, s2])

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [8]:
pd.concat([s1,s2], axis= 1)

0      1
A  100.0    NaN
B  200.0    NaN
C  300.0    NaN
D    NaN  400.0
E    NaN  500.0

In [9]:
#Concatenation of Pandas DataFrames
df1= DataFrame(np.random.randn(12).reshape(4,3), columns= list("ABC"))
df2= DataFrame(np.arange(9).reshape(3,3), columns= list("ABD"))
print(df1)
print(df2)

          A         B         C
0 -1.608966  1.666608  0.766688
1 -1.745880  0.358967  0.974245
2  1.819587  0.776130  1.311916
3 -0.134004 -0.177964  0.054900
   A  B  D
0  0  1  2
1  3  4  5
2  6  7  8


In [10]:
pd.concat([df1, df2])

A         B         C    D
0 -1.608966  1.666608  0.766688  NaN
1 -1.745880  0.358967  0.974245  NaN
2  1.819587  0.776130  1.311916  NaN
3 -0.134004 -0.177964  0.054900  NaN
0  0.000000  1.000000       NaN  2.0
1  3.000000  4.000000       NaN  5.0
2  6.000000  7.000000       NaN  8.0

In [11]:
pd.concat([df1, df2], ignore_index= True)

A         B         C    D
0 -1.608966  1.666608  0.766688  NaN
1 -1.745880  0.358967  0.974245  NaN
2  1.819587  0.776130  1.311916  NaN
3 -0.134004 -0.177964  0.054900  NaN
4  0.000000  1.000000       NaN  2.0
5  3.000000  4.000000       NaN  5.0
6  6.000000  7.000000       NaN  8.0

In [12]:
pd.concat([df1, df2], axis= 1)

A         B         C    A    B    D
0 -1.608966  1.666608  0.766688  0.0  1.0  2.0
1 -1.745880  0.358967  0.974245  3.0  4.0  5.0
2  1.819587  0.776130  1.311916  6.0  7.0  8.0
3 -0.134004 -0.177964  0.054900  NaN  NaN  NaN