In [1]:
#Agenda
#Populate a list based on conditional values
#Disadvantages
#Using np.where()
#Standard functionss in numpy- sum, sum(0), mean(), std(), var()
#Logiical AND, OR Operation- any(), all()
#sort() function
#unique()
#in1d()

In [2]:
import numpy as np

In [3]:
#Populate a list based on conditional values

x= np.array([100,400,-50,-40]) #each element called a
y= np.array([10,15,20,25]) #each element called b
condition= np.array([True, True, False, False]) #each element called cond

z= [a if cond else b for a,cond,b in zip(x,condition,y)]
print(z)

[100, 400, 20, 25]


In [4]:
#Disadvantages
#    Very tedious

In [5]:
#Using np.where(condtion, values for true, values for false)

z2= np.where(condition, x, y)
print(z2)

[100 400  20  25]


In [6]:
z3= np.where(x> 0, x, y)
print(z2)

[100 400  20  25]


In [7]:
#Standard functionss in numpy- sum, sum(0), mean(), std(), var()

print(x.sum())

410


In [8]:
x2= np.array([[1,2], [3,4]])
print(x2)

[[1 2]
 [3 4]]


In [9]:
print(x2.sum(0)) #Sum along the columns

[4 6]


In [10]:
print(x.mean())
print(x.std())
print(x.var())

102.5
181.71062159378576
33018.75


In [11]:
#Logiical AND, OR Operation- any(), all()

condition2= np.array([True, False, True])

#OR
print(condition2.any())

#AND
print(condition2.all())

True
False


In [12]:
#sort() function

unsorted= np.array([1,2,10,6,4,3])
print(unsorted)
unsorted.sort()
print(unsorted)

[ 1  2 10  6  4  3]
[ 1  2  3  4  6 10]


In [13]:
#unique()

arr2= np.array(['liquid', 'liquid', 'liquid', 'gas', 'gas', 'solid', 'solid'])
print(np.unique(arr2))

['gas' 'liquid' 'solid']


In [14]:
#in1d() => used to check whether list of elements are present or not

print(np.in1d(['solid', 'liquid', 'plasma'], arr2))

[ True  True False]
