In [1]:
#Agenda
#Recap of Previous video and intro to current video
#Accessing Rows
#Accessing elements of Array
#Slicing in 2D Arrays
#Using Loops to change index
#Accessing rows using list of index values
#Summary
#What's next

In [2]:
import numpy as np

In [3]:
arr2D= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Accessing Rows
print(arr2D[0])
print(arr2D[1])

[1 2 3]
[4 5 6]


In [5]:
#Accessing elements of Array
print(arr2D[0][0])
print(arr2D[1][2])

1
6


In [6]:
#Slicing in 2D Arrays
slice1= arr2D[0:1, 0:2]
print(slice1,"\n")

slice2= arr2D[0:2, 0:3]
print(slice2)

[[1 2]] 

[[1 2 3]
 [4 5 6]]


In [7]:
slice3= arr2D[:2, :3]
print(slice3)

[[1 2 3]
 [4 5 6]]


In [8]:
slice4= arr2D[1:, 2:]
print(slice4)

[[6]
 [9]]


In [9]:
#Using Loops to change index

arr_len= arr2D.shape
print(arr_len)
nrows= arr_len[0]

(3, 3)


In [10]:
for i in range(nrows):
    arr2D[i][0]= i
print(arr2D)

[[0 2 3]
 [1 5 6]
 [2 8 9]]


In [11]:
#Accessing rows using list of index values

print(arr2D[[0,1]])

[[0 2 3]
 [1 5 6]]


In [12]:
print(arr2D[[1,0]])

[[1 5 6]
 [0 2 3]]
