In [1]:
#Agenda
#Introduction to Numpy
#Creating 1D Numpy Array
#Creating 2D Numpy Array
#Finding Dimensions of Array- shape
#Finding Datatype of Array- dtype
#Array Creation and Initialization Functions- zeros
#Array Creation and Initialization Functions- ones
#Array Creation and Initialization Functions- empty
#Array Creation and Initialization Functions- eye
#Array Creation and Initialization Functions- arange
#Summarize

In [2]:
import numpy as np

In [3]:
#Creating 1D Numpy Array

mylist1= [101,102,103]

myArray= np.array(mylist1)

print(myArray)

[101 102 103]


In [4]:
#Creating 2D Numpy Array

mylist2= [201,202,203]

myArray2D= np.array([mylist1, mylist2])

print(myArray2D)

[[101 102 103]
 [201 202 203]]


In [5]:
#Finding Dimensions of Array- shape
print("myArray Dimensions")
print(myArray.shape)
print("myArray2D Dimensions")
print(myArray2D.shape)

myArray Dimensions
(3,)
myArray2D Dimensions
(2, 3)


In [6]:
#Finding Datatype of Array- dtype
print("myArray Datatype")
print(myArray.dtype)
print("myArray2D Datatype")
print(myArray2D.dtype)

myArray Datatype
int32
myArray2D Datatype
int32


In [7]:
#Array Creation and Initialization Functions- zeros
print("1D")
zero_array= np.zeros(5)
print(zero_array,"\n")
print("2D")
zero_array2D= np.zeros([5,5])
print(zero_array2D)

1D
[0. 0. 0. 0. 0.] 

2D
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#Array Creation and Initialization Functions- ones
print("1D")
one_array= np.ones(5)
print(one_array,"\n")
print("2D")
one_array2D= np.ones([5,5])
print(one_array2D)

1D
[1. 1. 1. 1. 1.] 

2D
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
#Array Creation and Initialization Functions- empty
print("1D")
empty_array= np.empty(5)
print(empty_array,"\n")
print("2D")
empty_array2D= np.empty([5,5])
print(empty_array2D)

1D
[1. 1. 1. 1. 1.] 

2D
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
#Array Creation and Initialization Functions- eye (Identity Matrix)

Identity_array= np.eye(3)
print(Identity_array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#Array Creation and Initialization Functions- arange

AP_array= np.arange(0,50,2)
print(AP_array)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
