In [1]:
#Agenda
#Introduction to Indexes
#Access Individual Array Elements
#Slicing of Array Indexes arr[start:stop:step]
#Updating Array Using Slices
#Interesting point about Slicing- Memory Allocation - View Vs. Copy
#Advantages
#copy() function => Creating new numpy memory for array

In [2]:
import numpy as np

In [3]:
arr= np.arange(100,160,2)
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [4]:
#Introduction to Indexes

In [5]:
#Access Individual Array Elements

print("First Element")
print(arr[0])
print("Second Element")
print(arr[1])
print("Third Element")
print(arr[2])
print("Fifth Element")
print(arr[4])

First Element
100
Second Element
102
Third Element
104
Fifth Element
108


In [6]:
#Slicing of Array Indexes arr[start:stop:step]

print(arr[0:5:1])

[100 102 104 106 108]


In [7]:
#Updating Array Using Slices

arr[0:5]= 0
print(arr)

[  0   0   0   0   0 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [8]:
#Interesting point about Slicing- Memory Allocation - View Vs. Copy

arr2= arr[4:10]
print(arr2)
arr2[:]= 1
print(arr2)
print(arr)

[  0 110 112 114 116 118]
[1 1 1 1 1 1]
[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [9]:
#copy() function => Creating new numpy memory for array

arr3= arr.copy()
print(arr3)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [10]:
arr3[:]= 0
print(arr3)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]
