In [1]:
#Agenda
#Function of Numpy Arrays - arange()
#Function of Numpy Arrays - sqrt()
#Function of Numpy Arrays - exp()
#Function of Numpy Arrays - random()
#Function of Numpy Arrays - add()
#Function of Numpy Arrays - maximum()
#Numpy Additional documentation - numpy.org, docs.scipy.org

In [2]:
import numpy as np

In [3]:
#Function of Numpy Arrays - arange()

A= np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
B= np.arange(5, 10)
print(B)

[5 6 7 8 9]


In [5]:
C= np.arange(5,10,2)
print(C)

[5 7 9]


In [6]:
#Function of Numpy Arrays - sqrt()

D= np.sqrt(A)
print(D)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [7]:
#Function of Numpy Arrays - exp()

E= np.exp(A)
print(E)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


In [9]:
#Function of Numpy Arrays - random()

F= np.random.randn(5)
print(F,"\n")

G= np.random.randn(5,5)
print(G)

[-1.10485596  0.1576654   0.41301919 -0.19311083  1.51621386] 

[[ 0.50273973  0.84686367  0.40456967  0.34830885  1.16942311]
 [-1.39793719 -0.98408966 -0.27836701  2.00444924 -0.25829396]
 [-1.68198646  2.03245723  0.71462312  0.62212081 -1.28268707]
 [ 1.88014113  1.3990372  -1.43009706  0.05101544  0.60716431]
 [ 0.59263724  0.23754571 -0.3027718   0.93509845  0.04891617]]


In [10]:
#Function of Numpy Arrays - add()
print(A,"\n")
print(D, "\n")
G= np.add(A,D)
print(G)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739] 

[ 0.          2.          3.41421356  4.73205081  6.          7.23606798
  8.44948974  9.64575131 10.82842712 12.         13.16227766 14.31662479
 15.46410162 16.60555128 17.74165739]


In [11]:
#Function of Numpy Arrays - maximum()

A= np.array([1,5,7,10])
B= np.array([0, 6, 8, 9])
H= np.maximum(A, B)
print(H)

[ 1  6  8 10]
