In [1]:
#Agenda
#What is Pandas
#What is Series
#Install Pandas
#Create a simple series variable
#Create series from numpy
#Create series with custom indexes
#Filter a Series based on conditions
#Check whether an element is in a series
#to_dict() function
#Addition of 2 series
#Assign names to a Series and its Index

In [2]:
import numpy as np
import pandas as pd

In [3]:
#What is Pandas
#What is Series
from pandas import Series

In [4]:
#Create a simple series variable
s1= Series([5,10,15,20])
print(s1)

0     5
1    10
2    15
3    20
dtype: int64


In [5]:
print(s1.values)

[ 5 10 15 20]


In [6]:
print(s1.index.values)

[0 1 2 3]


In [7]:
#Create series from numpy
revenue_array= np.array([400,300,200,100])
print(revenue_array)

[400 300 200 100]


In [8]:
revenue_series= Series(revenue_array)
print(revenue_series)

0    400
1    300
2    200
3    100
dtype: int32


In [9]:
#Create series with custom indexes
revenue= Series(revenue_array,index=["uber", "ola", "lyft", "gojek"])
print(revenue)

uber     400
ola      300
lyft     200
gojek    100
dtype: int32


In [10]:
revenue["ola"]

300

In [11]:
revenue["gojek"]

100

In [12]:
#Filter a Series based on conditions
print(revenue[revenue > 250])

uber    400
ola     300
dtype: int32


In [13]:
#Check whether an element is in a series
print("ola" in revenue)

True


In [14]:
print("grab" in revenue)

False


In [15]:
#to_dict() function
revenue_dict= revenue.to_dict()
print(revenue_dict)

{'uber': 400, 'ola': 300, 'lyft': 200, 'gojek': 100}


In [16]:
#Addition of 2 series
print(revenue)
print(revenue + revenue)

uber     400
ola      300
lyft     200
gojek    100
dtype: int32
uber     800
ola      600
lyft     400
gojek    200
dtype: int32


In [17]:
#Assign names to a Series and its Index
revenue.name= "Company- Revenue"
print(revenue)

uber     400
ola      300
lyft     200
gojek    100
Name: Company- Revenue, dtype: int32


In [18]:
revenue.index.name= "Company Name"
print(revenue)

Company Name
uber     400
ola      300
lyft     200
gojek    100
Name: Company- Revenue, dtype: int32
